### ISSUE TITLE
Use git instead of rsync for gentoo repo

### ISSUE THREAD

**Issue by bedroge** [EESSI/compatibility-layer#100]
Running `emerge --sync` can be incredibly slow in, for instance, Github Actions (usually takes ~3-4h). It could be worth trying to use git instead, see:

https://forums.gentoo.org/viewtopic-t-1101600-start-0.html
https://wiki.gentoo.org/wiki/Project:Portage/Repository_verification
https://wiki.gentoo.org/wiki/Portage_Security#git-mirror_repositories
https://www.reddit.com/r/Gentoo/comments/k9b8zx/switched_from_rsync_to_git_for_gentoo_repo_got/
https://www.serra.me/en/2020/01/gentoo-use-git-for-portage-synchronization/
https://www.reddit.com/r/Gentoo/comments/7xa6p9/emerge_sync_taking_too_long/

**Comment by amadio** [comment]
Syncing with rsync is slow because it does repository verification, but you can disable that if you want to keep using rsync.
However, I think that using git is better indeed. Here's a quick example of how to setup the main repo using git:
```
[DEFAULT]
main-repo = gentoo
sync-git-pull-extra-opts = --quiet

[gentoo]
priority  = 1
location  = /cvmfs/sft.cern.ch/lcg/contrib/gentoo/portage/gentoo
sync-uri  = https://github.com/gentoo/gentoo.git
sync-type = git
auto-sync = Yes
clone-depth = 1
```
Should be quite easy to change. However, some metadata is generated on the fly, so you might want to take a look at hasufell's scripts to be used in conjunction: https://github.com/hasufell/portage-gentoo-git-config. I've been using this type of setup since a while.

**Comment by bedroge** [comment]
Thanks! I'll look into that and try it out on a local installation.

**Comment by bedroge** [comment]
Did a quick test with this, and by switching to git, my Github Action that previously took 3-4 hours now completed in 10 minutes. We should change this for our next pilot.
