### ISSUE TITLE
/etc/passwd userid issue

### ISSUE THREAD

**Issue by JvD007** [EESSI/compatibility-layer#15]
Gentoo user prompt is wrong, Name is not from the local /etc/passwd.

dell@Innopad-01:~$ /cvmfs/pilot.eessi-hpc.org/test/gentoo/2020/startprefix
Entering Gentoo Prefix /cvmfs/pilot.eessi-hpc.org/test/gentoo/2020

**henkjan@Innopad-01:~$**
User is coming  from /cvmfs/pilot.eessi-hpc.org/test/gentoo/2020/etc/passwd.

**I have no name!@Innopad-01:/mnt/c/Users/Innopad$**

User is not in the /etc/passwd file coming from /cvmfs/pilot.eessi-hpc.org/test/gentoo/2020/etc/passwd.

Can we use the local /etc/passwd file?

**Comment by boegel** [comment]
I used this (dirty) hack when installing stuff in the pilot repo:

```
getent passwd $(id -u) >> /cvmfs/pilot.eessi-hpc.org/2020.08/compat/x86_64/etc/passwd
```

Of course that only works if you have write access to `/cvmfs` (for example via a writable overlay created with `fuse-overlayfs`).

Perhaps symlinking to the system `/etc/passwd` is a good idea, but I don't think that will be enough (no all user accounts are listed in `/etc/passwd`).

**Comment by boegel** [comment]
@bartoldeman Is there any documentation available on why each of these should be symlinked?

The only one I know why really is `/etc/passwd` (to make sure the local user accounts are known)...

**Comment by bartoldeman** [comment]
Many of these (the ones involving /var) I consider bugs in the gentoo prefix recipes, though it depends a bit on the use case.
So some packages could be compiled with `--localstatedir=/var` instead of `--localstatedir=${EPREFIX}/var` passed to configure to avoid some of the links.

Similarly for sysconfdir (/etc) but it depends a lot, some things in /etc are static (so can be in cvmfs), some are system dependent, etc.

Files like `/var/log/wtmp` and `/var/run/utmp` are written to by the system but read by utilities in the compatibility layer such as `w`, `last` and `who`. It's all been a bit of trial and error, and a bit of strace.

**Comment by bedroge** [comment]
This should be solved by #37 and #38 and. You can try it in the 2020.09 version of our pilot (`/cvmfs/pilot.eessi-hpc.org/2020.09/compat/x86_64`).

**Comment by bedroge** [comment]
@JvD007 Could you test if this also solves the issue for you?

**Comment by JvD007** [comment]
How! like source /cvmfs/pilot.eessi-hpc.org/2020.09/init/bash or......

**Comment by bedroge** [comment]
That doesn't work yet, but there is a `startprefix` that should allow you to test it:
`/cvmfs/pilot.eessi-hpc.org/2020.09/compat/x86_64/startprefix`

**Comment by JvD007** [comment]
Works
![image](https://user-images.githubusercontent.com/47723062/94236227-2a721a00-ff0d-11ea-807e-ee64b95cf210.png)

**Comment by boegel** [comment]
@bedroge OK to close this then?

**Comment by bedroge** [comment]
Yes, think so, though we may still need some more symlinks later on.
