### ISSUE TITLE
Add rpm.ebuild to compat layer

### ISSUE THREAD

**Issue by ocaisa** [EESSI/compatibility-layer#151]
For GPU support we need to be able to unpack RPMs

**Comment by boegel** [comment]
Rather than installing a tool that's specific to unpacking RPMs, and using other stuff for unpacking `.deb` packages, how about using one tool for all types of packages, like `alien` mentioned by @sassy-crick, or [`fpm`](https://github.com/jordansissel/fpm) (I didn't check whether `fpm` supports unpacking of package files, but I would imagine it does).

**Comment by ocaisa** [comment]
We can already unpack deb packages with `ar`/`tar`. I'm easy though, as long as it does the job, I don't care. I just saw there was already an ebuild for that.

**Comment by ocaisa** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-arch/alien/alien-8.95-r1.ebuild Alien is there too but also pulls in other deps (such as the `rpm.ebuild`)...

**Comment by ocaisa** [comment]
No need for this, we use p7zip shipped with EESSI for this going forward
