### ISSUE TITLE
Prefix installation method

### ISSUE THREAD

**Issue by bedroge** [EESSI/compatibility-layer#3]
Here we can discuss how we are going to install Prefix. Do we, for instance, copy the bootstrap script to our repo and customize it to our needs, or do we use some other mechanism to install it?

**Comment by lexming** [comment]
I've seen in the documentation of the project that we plan to support multiple OS and architectures. However, the use case of the compatibility layer is not clear to me. Should it be possible for regular users to install the compatibility layer in their laptops? or will it be used a system-wide service managed by administrators?

Furthermore, what are the boundaries of the compatibility-layer project? mainly I would like to know if the host system is off-limits. Should we work with whatever is provided by the host or can we provide VMs or other resources below the compatibility-layer?

The bootstrap scrip from the Gentoo Prefix project is a solid starting point, it has already code in place handling different OS, can be used by regular users and upstream seems to be very responsive. IMO its weak point is its exposure to the host system (eg I had issues because my host has a relatively exotic locale) and the requirements on the host system, which has to have a working build environment with `gcc`.

Depending on the goals of the project, there are other options to generate the Gentoo environment
* run the bootstrap scrip inside a container to have more control over the host system
* use a stage 3 tarball and chroot into it (with a systemd-nspawn service for instance), this method requires root but does not rely as much in the host system

**Comment by boegel** [comment]
@lexming The compatibility layer is a part of the distributed filesystem that is provided through CVMFS, so clients don't have to install that at all, they just need mount the filesystem.

While we still need to figure out a way to handle the installation of Gentoo Prefix and managing the packages we install in the compatibility layer, it should work seamlessly for clients, no matter what is in the host OS.

I think our best way forward to maintain the compatibility layer is indeed getting Gentoo Prefix installed in a controlled environment, a container image should make that easy (but not a general solution, that won't work to support macOS or WSL clients for example).

The scientific software provided in the software layer will only link to libraries provided in the compatibility layer (like `libc`), not from the host OS, which is how we make the scientific software stack compatible with many different clients.

There are some exceptions (like kernel modules, IB drivers, GPU drivers, etc.), but what is required by the clients is minimal (see for example the [Compute Canada documentation])(https://docs.computecanada.ca/wiki/Accessing_CVMFS#CVMFS_requirements)), it basically boils down to having CVMFS installed to mount the filesystem.

@bartoldeman @mboisson Is there a more detailed list of requirements for clients, like minimal kernel version, etc.?

**Comment by bartoldeman** [comment]
The minimal kernel version is mainly determined by the version of glibc, see e.g.
https://man7.org/tlpi/api_changes/index.html
glibc >= 2.26 needs at least Linux kernel 3.2 (CentOS-7 has 3.10)
glibc >= 2.24 needs at least 2.6.32 on x86, 3.2 on other arches
glibc >= 2.20 needs at least 2.6.32 (CentOS-6 has that kernel)
glibc >= 2.17 needs at least 2.6.16 (CentOS-5 has 2.6.18)
glibc >= 2.16 needs at least 2.6.0
(I don't think I want to go further back than that..., we are already in 2012 here on the glibc side, and 2003 on the kernel side here :) )
Gentoo prefix has some functionality for that if you have to but I don't think you really want to support CentOS-6 any more: if you install glibc 2.25 you can but glibc 2.29+ have a lot of improvements on the math side which you'd lose.

**Comment by bartoldeman** [comment]
Agreed on the singularity container by the way, the bootstrap is most reliable if you have the bare minimum installed in terms of development packages -- on our build-node we have zero development rpms installed but for a bootstrap you need at least gcc and glibc-devel for sure.

**Comment by bartoldeman** [comment]
also, some symlinks are needed to interact with the host LDAP, e.g. using scripting like this:
```
               if [ ! -f "${ROOT}"/etc/nsswitch.conf.unused ]; then
                       mv "${ROOT}"/etc/nsswitch.conf "${ROOT}"/etc/nsswitch.conf.unused
                       ln -s /etc/nsswitch.conf "${ROOT}"/etc/nsswitch.conf
                       ln -s /lib64/libnss_ldap.so.2 "${ROOT}"/lib64/libnss_ldap.so.2
                       ln -s /lib64/libnss_sss.so.2 "${ROOT}"/lib64/libnss_sss.so.2
              fi
```
Similarly there are some directories in $EPREFIX/var that need to symlinked to the host system (mail, run, spool, and tmp for sure), otherwise things like `who` and `w` don't work, or anything else that uses `/var/run/utmp`.

**Comment by bartoldeman** [comment]
(or modify the ebuilds for those so they use /var instead of $EPREFIX/var, but I found that more complicated...)

**Comment by boegel** [comment]
For installing prefix on macOS, this could be interesting to do it in a controlled/clean environment: https://github.com/geerlingguy/macos-virtualbox-vm

**Comment by peterstol** [comment]
> Following discussion of #2 , here there are some CI scripts that may be useful: https://github.com/awesomebytes/gentoo_prefix_ci
> 
> It could be convenient to run the CI daily or weekly and store the bootstrap-prefix.sh and the portage-latest.tar.bz2 in case the bootstrap process is broken in the future and we're in the need to boostrap prefix again. The bootstrap-prefix.sh script can be modified to use a local portage file instead of downloading the latest one.

That looks very promising Carlos!

**Comment by bedroge** [comment]
This no longer seems relevant, so I'm closing this issue.
