### ISSUE TITLE
Add `/opt/eessi/2021.03/lib` to `prefix_user_defined_trusted_dir`

### ISSUE THREAD

**Issue by ocaisa** [EESSI/compatibility-layer#92]
`prefix_user_defined_trusted_dir` currently only takes `/opt/eessi/lib` as an option, but this does not allow the possibility of having release specifc changes (for example overriding the MPI with another ABI compatible one). We should also allow `/opt/eessi/2021.03/lib` to address this.

I guess the option should then be `prefix_user_defined_trusted_dirs` and some docs about how the list is separated

**Comment by bedroge** [comment]
I have a commit in PR #91 that adds the EESSI pilot version to the path, see: https://github.com/EESSI/compatibility-layer/pull/91/commits/a30b8a46030a590d1f33f146a928ce26c7694c95

I imagine it could indeed even make sense to allow both, so that you by default get the generic stuff from `/opt/eessi/lib`, but you can also override it for a specific version. I can see if it's easy to change this into a list.
